//! Tests for the MP3 half, against small synthetic fixtures.
//!
//! Generated by ffmpeg from `sine`, so they carry nobody's content and are small enough to commit —
//! the same rule `km-video`'s `tone.mp4` follows. Regenerate with:
//!
//! ```sh
//! cd crates/playback/km-cdg/fixtures
//! S="sine=frequency=440:sample_rate=44100:duration=2"
//! # `volume=8` because ffmpeg's `sine` comes out around -21 dB, which is too quiet for a peak
//! # assertion to mean anything.
//! ffmpeg -f lavfi -i "$S" -af volume=8 -ac 2 -c:a libmp3lame -b:a 128k tone.mp3
//! ffmpeg -f lavfi -i "$S" -af volume=8 -ac 2 -c:a libmp3lame -b:a 128k \
//!        -metadata title="Tone Fixture" -metadata artist="Sine Wave" tagged.mp3
//! ffmpeg -f lavfi -i "$S" -af volume=8 -ac 2 -c:a libmp3lame -b:a 128k -write_xing 0 noxing.mp3
//! ffmpeg -f lavfi -i "sine=frequency=330:sample_rate=44100:duration=1" \
//!        -af volume=8 -ac 1 -c:a libmp3lame -b:a 64k mono.mp3
//! ```
//!
//! The real corpus is validated by `examples/decode`, which is where the interesting numbers came
//! from: a six-minute song renders to within 0.1 s of its probed length with no starved frames, and
//! its levels land within 0.02 dB of ffmpeg's own decode of the same file.

use std::path::{Path, PathBuf};

use km_audio::TrackPlayer;

use super::*;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join(name)
}

/// Renders a whole fixture through a real player, the way `examples/decode` does.
///
/// Paced for the reason that example documents: pulling flat out beats the decoder and the player
/// answers an empty ring with silence, which is right for a live machine and useless in a test.
fn render(path: &Path, rate: u32) -> Vec<f32> {
    let (_reader, feed, _frames) = open_audio(path).map(|(r, f)| (r, f, ())).expect("opens");
    let mut player = TrackPlayer::new(feed, rate);
    std::thread::sleep(StdDuration::from_millis(200));

    let mut samples = Vec::new();
    let mut left = vec![0.0f32; 1024];
    let mut right = vec![0.0f32; 1024];
    // Generous: the fixtures are two seconds and this only bounds a runaway.
    for _ in 0..1_000 {
        if player.is_finished() {
            break;
        }
        player.render(&mut left, &mut right, true);
        samples.extend(left.iter().zip(&right).flat_map(|(l, r)| [*l, *r]));
        std::thread::sleep(StdDuration::from_millis(2));
    }
    assert_eq!(player.starved_frames(), 0, "the decoder fell behind");
    samples
}

fn peak(samples: &[f32]) -> f32 {
    samples.iter().fold(0.0f32, |peak, s| peak.max(s.abs()))
}

/// The reader form and the path form agree about a file's shape.
///
/// This is what moving media into the `.kmpkg` asks of this crate: the packaged route hands over a
/// window into an archive instead of a file, and nothing downstream may be able to tell.
#[test]
fn a_reader_probes_to_the_same_shape_as_a_path() {
    let by_path = probe_audio(&fixture("tone.mp3")).expect("path");
    let file = std::fs::File::open(fixture("tone.mp3")).expect("open");
    let by_reader = probe_audio_from(file, "media/0012.mp3").expect("reader");
    assert_eq!(by_path, by_reader);
}

/// The wrapper reports a length and admits to being seekable.
///
/// `is_seekable` is the load-bearing half: `format.seek` is how a rewind mid-song works, and
/// symphonia asks the source rather than trying it. A wrapper that said `false` would leave rewind
/// silently doing nothing rather than failing.
#[test]
fn the_media_source_wrapper_is_seekable_and_knows_its_length() {
    let bytes = std::fs::read(fixture("tone.mp3")).expect("read");
    let len = bytes.len() as u64;
    let source = Seekable::new(std::io::Cursor::new(bytes)).expect("wrap");
    assert!(source.is_seekable());
    assert_eq!(source.byte_len(), Some(len));
}

/// And a song decodes from a reader, seek included.
///
/// Decoding is what a probe cannot exercise, because a probe finishes before the decoder thread
/// starts; the seek is what proves the wrapper's `is_seekable` reached symphonia intact.
#[test]
fn a_song_decodes_and_seeks_through_a_reader() {
    let bytes = std::fs::read(fixture("tone.mp3")).expect("read");
    let (format, track_id) =
        crate::audio::open_format_from(std::io::Cursor::new(bytes), "media/0012.mp3")
            .expect("open");
    let (reader, feed) =
        crate::audio::open_audio_from(format, track_id, "media/0012.mp3").expect("decode");

    let mut player = km_audio::TrackPlayer::new(feed, 44_100);
    let mut left = vec![0.0; 1024];
    let mut right = vec![0.0; 1024];
    let mut loudest = 0.0f32;
    for _ in 0..200 {
        player.render(&mut left, &mut right, true);
        loudest = loudest.max(peak(&left));
        if loudest > 0.01 {
            break;
        }
        std::thread::sleep(StdDuration::from_millis(5));
    }
    assert!(loudest > 0.01, "no audio came out of a reader-backed song");
    drop(reader);
}

#[test]
fn a_probe_reads_the_shape_of_a_file() {
    let info = probe_audio(&fixture("tone.mp3")).expect("probes");
    assert_eq!(info.sample_rate, 44_100);
    assert_eq!(info.channels, 2);
    assert_eq!(info.codec, "mp3");
    // Two seconds. Not exact to the millisecond: an MP3 is a whole number of 1,152-sample frames,
    // so the encoder pads the last one.
    assert!(
        (1_950..=2_100).contains(&info.duration_ms),
        "got {} ms",
        info.duration_ms
    );
}

#[test]
fn a_file_with_no_xing_header_still_reports_its_length() {
    // The fallback that walks the file summing packet durations. CBR rips in the real corpus often
    // have no Xing header, and a length guessed from the file size would be wrong by the size of
    // the ID3 tag.
    let stated = probe_audio(&fixture("tone.mp3"))
        .expect("probes")
        .duration_ms;
    let counted = probe_audio(&fixture("noxing.mp3"))
        .expect("probes")
        .duration_ms;
    assert!(
        counted.abs_diff(stated) <= 60,
        "counted {counted} ms against a stated {stated} ms"
    );
}

#[test]
fn tags_are_read_when_they_are_there_and_absent_when_they_are_not() {
    let tagged = probe_audio(&fixture("tagged.mp3")).expect("probes");
    assert_eq!(tagged.title.as_deref(), Some("Tone Fixture"));
    assert_eq!(tagged.artist.as_deref(), Some("Sine Wave"));

    // Same tone, no tags: `None` rather than an empty string, because a blank tag looks like an
    // answer and is not one.
    let plain = probe_audio(&fixture("tone.mp3")).expect("probes");
    assert_eq!(plain.title, None);
    assert_eq!(plain.artist, None);
    assert_eq!(plain.sample_rate, tagged.sample_rate);
}

#[test]
fn a_missing_file_is_an_error_rather_than_a_panic() {
    let error = probe_audio(&fixture("nothing-here.mp3")).expect_err("must fail");
    assert!(matches!(error, CdgError::Io { .. }), "got {error:?}");
}

#[test]
fn a_file_that_is_not_audio_is_refused_with_the_reason() {
    // The `.cdg` beside a song is the file most likely to be handed here by mistake.
    let error = probe_audio(&fixture("../src/audio.rs")).expect_err("must fail");
    assert!(
        matches!(
            error,
            CdgError::Undecodable { .. } | CdgError::NoAudioTrack { .. }
        ),
        "got {error:?}"
    );
}

#[test]
fn a_real_decode_produces_the_tone() {
    let samples = render(&fixture("tone.mp3"), 48_000);
    let frames = samples.len() / 2;
    assert!(
        (frames as f64 / 48_000.0 - 2.0).abs() < 0.1,
        "rendered {:.3}s",
        frames as f64 / 48_000.0
    );
    // A full-scale sine through an MP3 at 128 kbps comes back near enough to full scale. The point
    // is that it is signal and not silence, which is what a wrong sample format looks like.
    assert!(peak(&samples) > 0.5, "peak {}", peak(&samples));
}

#[test]
fn a_mono_file_is_duplicated_into_both_channels() {
    let samples = render(&fixture("mono.mp3"), 48_000);
    assert!(peak(&samples) > 0.5, "peak {}", peak(&samples));
    // Every frame is the same sample twice. Checked past the start, where the encoder's own
    // ramp-in makes the values too small to be interesting.
    let from = (samples.len() / 4) & !1;
    for frame in samples[from..].as_chunks::<2>().0.iter().take(2_000) {
        assert!(
            (frame[0] - frame[1]).abs() < f32::EPSILON,
            "channels differ: {} against {}",
            frame[0],
            frame[1]
        );
    }
}

#[test]
fn the_device_rate_never_reaches_the_decoder() {
    // The feed carries the file's rate and `TrackPlayer` resamples, so asking for an unusual output
    // rate changes the length of the render and nothing about the decode.
    let at_48 = render(&fixture("tone.mp3"), 48_000).len() / 2;
    let at_32 = render(&fixture("tone.mp3"), 32_000).len() / 2;
    let seconds_48 = at_48 as f64 / 48_000.0;
    let seconds_32 = at_32 as f64 / 32_000.0;
    assert!(
        (seconds_48 - seconds_32).abs() < 0.1,
        "{seconds_48:.3}s at 48 kHz against {seconds_32:.3}s at 32 kHz"
    );
}

#[test]
fn a_seek_lands_near_where_it_was_asked_to() {
    let (_reader, feed) = open_audio(&fixture("tone.mp3")).expect("opens");
    let mut player = TrackPlayer::new(feed, 48_000);
    std::thread::sleep(StdDuration::from_millis(200));

    player.seek_ms(1_000);
    std::thread::sleep(StdDuration::from_millis(300));

    let mut left = vec![0.0f32; 1024];
    let mut right = vec![0.0f32; 1024];
    let mut rendered = 0usize;
    for _ in 0..500 {
        if player.is_finished() {
            break;
        }
        player.render(&mut left, &mut right, true);
        rendered += left.len();
        std::thread::sleep(StdDuration::from_millis(2));
    }

    // One second in, one second left. A coarse seek lands at a frame boundary, not a sample one.
    let seconds = rendered as f64 / 48_000.0;
    assert!((0.8..=1.2).contains(&seconds), "rendered {seconds:.3}s");
    assert!(player.position_ms() >= 1_900, "{}", player.position_ms());
}

#[test]
fn dropping_the_reader_stops_the_thread() {
    // The reader joins on drop, so this hanging would be a deadlock rather than a slow test. It is
    // the invariant that makes it safe to drop a loaded song on the control thread.
    let (reader, feed) = open_audio(&fixture("tone.mp3")).expect("opens");
    drop(feed);
    drop(reader);
}

/// What the meter reports for the fixtures, and how it relates to what ffmpeg says.
///
/// **The measurement is of the samples the machine will play, not of the file.** For a stereo file
/// those are the same thing and the numbers match ffmpeg's `ebur128` directly:
///
/// ```sh
/// ffmpeg -hide_banner -nostats -i tone.mp3 -filter_complex ebur128=peak=true -f null -
/// #   I: -4.1 LUFS      Peak: -3.5 dBFS
/// ```
///
/// **A mono file is where the distinction bites, and it is not a disagreement.** [`append`]
/// duplicates a mono channel into both at full amplitude, which R128 reads as 3 dB louder than the
/// one channel — and it is, through two speakers. `ffmpeg -i mono.mp3` measures the file at −4.2
/// LUFS and even `-ac 2` still says −4.2, because ffmpeg's upmix scales each channel by −3 dB to
/// hold the loudness constant. This machine does not: it duplicates, so it plays the mono fixture
/// about 3 dB louder than ffmpeg would, and the number recorded has to be the one the gain will be
/// applied to.
#[test]
fn the_meter_measures_what_the_machine_will_play() {
    let stereo = measure_loudness(&fixture("tone.mp3"))
        .expect("the fixture decodes")
        .expect("two seconds is enough to integrate");
    assert!(
        (stereo.lufs - (-4.1)).abs() < 0.2,
        "tone.mp3 measured {} LUFS, ffmpeg says -4.1",
        stereo.lufs
    );
    assert!(
        (stereo.peak_dbtp - (-3.5)).abs() < 0.3,
        "tone.mp3 peaked at {} dBTP, ffmpeg says -3.5",
        stereo.peak_dbtp
    );

    let mono = measure_loudness(&fixture("mono.mp3"))
        .expect("the fixture decodes")
        .expect("one second is enough to integrate");
    assert!(
        (mono.lufs - (-4.2 + 3.01)).abs() < 0.3,
        "mono.mp3 measured {} LUFS; duplicating one channel into two should read about 3 dB above \
         ffmpeg's -4.2",
        mono.lufs
    );
}

/// A path and a window into a package measure the same file identically.
///
/// The two entry points are what `km-pack` uses for a build and for a re-analysis, and a re-analysis
/// reads the media out of an archive rather than off the disk. A number that depended on which way
/// in it came would make a rebuilt package disagree with a re-analysed one.
#[test]
fn measuring_through_a_reader_matches_measuring_a_path() {
    let path = fixture("tone.mp3");
    let by_path = measure_loudness(&path).expect("decodes").expect("measures");

    let file = std::fs::File::open(&path).expect("opens");
    let by_reader = measure_loudness_from(file, "media/0001.mp3")
        .expect("decodes")
        .expect("measures");

    assert_eq!(by_path, by_reader);
}

/// A file that is not audio is refused rather than measured as silence.
#[test]
fn measuring_something_that_is_not_audio_is_an_error() {
    assert!(measure_loudness(&fixture("../Cargo.toml")).is_err());
}
