//! Renders the Android TV launcher banner.
//!
//! ```text
//! cargo run -p km-display --example banner -- \
//!     ports/machine/android/app/src/main/res/drawable-xhdpi/banner.png
//! ```
//!
//! The leanback launcher requires a 320×180 xhdpi banner **with the name in the image** — it draws no
//! label of its own. Generating it from the display's own [`Theme`] and font rather than drawing one
//! by hand means the tile on the television's home row looks like the app it launches, and stays
//! looking like it if the theme changes.
//!
//! **The colors are the theme's and the point size is not**, which is the one deliberate departure
//! from that. The name is one line in two colors — the halves of `KaraokeMachine` set touching, so
//! it reads as the single word it is while keeping the two-tone mark — and at the themed size it
//! does not fit beside the icon. It is fitted by measurement instead: see the block that draws it
//! for why the overflow cannot be corrected by picking a smaller number here.
//!
//! **`Machine` is the sung-lyric amber, and it was the accent blue until the icon caught it out.**
//! The website's `<h1>` has always set that half in the amber, and the application icon now paints
//! its **M** in it too — so a banner in blue put a blue `Machine` beside an amber one in the same
//! 320 pixels. One name, one color.
//!
//! The icon comes from `icon/icon-128.png`, which the `icon` example renders. Blitting the finished
//! icon rather than drawing it again here is the point: a banner with a *different* mark on it would
//! be worse than one with none, and there is only one place the artwork is defined. Regenerate the
//! icon first if it has changed.
//!
//! Committed as a PNG, because it is an asset rather than a build product: Gradle needs it present in
//! `res/`, and nobody should need a Rust toolchain to build the APK.

use std::path::PathBuf;

use km_display::text::{Align, TextCache, TextStyle, draw_text, find_font, measure_line};
use km_display::theme::Theme;
use sdl3::pixels::PixelFormat;
use sdl3::render::FRect;
use sdl3::surface::Surface;

/// The size the leanback launcher wants at xhdpi.
const WIDTH: u32 = 320;
const HEIGHT: u32 = 180;

/// Clear air between the name and the right edge, so the mark is not read as touching the frame.
const EDGE_PAD: f32 = 8.0;

/// Below this the name is a smudge on a television across a room, and a tile with no legible name
/// is worse than a build that stops and says so.
const MIN_TEXT_PX: u16 = 12;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = std::env::args().nth(1).map_or_else(
        || PathBuf::from("ports/machine/android/app/src/main/res/drawable-xhdpi/banner.png"),
        PathBuf::from,
    );
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let _sdl = sdl3::init()?;
    let ttf = sdl3::ttf::init()?;
    let theme = Theme::default();

    let format = PixelFormat::try_from(sdl3::sys::pixels::SDL_PIXELFORMAT_ARGB8888)?;
    let surface = Surface::new(WIDTH, HEIGHT, format)?;
    let mut canvas = surface.into_canvas()?;
    let creator = canvas.texture_creator();
    // One frame, then thrown away -- but the two strings below are each drawn twice for their
    // outline, so even here it halves the work. Cleared before the canvas goes: these textures have
    // no `Drop`.
    let mut cache = TextCache::new(canvas.texture_creator());

    canvas.set_draw_color(theme.background);
    canvas.clear();

    // The icon on the left, so the tile is recognizable at a glance in a row of other apps before
    // anybody reads it. This replaced a plain band of the accent color, which was recognizable only
    // as "not the other tiles".
    let icon_size = HEIGHT as f32 * 0.72;
    let icon_x = WIDTH as f32 * 0.055;
    match icon_texture(&creator) {
        Ok(icon) => {
            let target = FRect::new(
                icon_x,
                (HEIGHT as f32 - icon_size) / 2.0,
                icon_size,
                icon_size,
            );
            let _ = canvas.copy(&icon, None, target);
        }
        // Reported rather than fatal, and it says what to run: the banner is still a usable tile
        // with the name on it, and failing the whole example over the picture would be the wrong
        // trade for something regenerated by hand.
        Err(error) => eprintln!(
            "banner: no icon ({error}); \
             run `cargo run -p km-display --example icon` first. Continuing without it."
        ),
    }

    // The name goes on one line to the right of the icon, in two colors -- so the tile still
    // carries the two-tone mark it always had, while the words read as the single word they now
    // are. `measure_line` measures *prefixes*, so `offsets[1]` is where `Machine` actually starts
    // with the kerning between the halves included, and nothing has to be guessed.
    //
    // **The size is fitted rather than taken from the theme**, which is the one thing here that is
    // not the display's own arithmetic. `KaraokeMachine` is fourteen characters where `Karaoke` was
    // seven, and at the themed size it overruns the ~172 px left beside the icon by about a third.
    // Worse, it is not knowable at write time by how much: `find_font` picks whatever this machine
    // has out of `CANDIDATES`, and Segoe UI is some 8% narrower than DejaVu Sans, so a size tuned
    // by hand would be right on one box and clipped on the next. So it descends from the themed
    // size and takes the first that measures inside the space.
    let text_left = icon_x + icon_size;
    let available = WIDTH as f32 - text_left - EDGE_PAD;
    let path = find_font(None, None).ok_or("no font found to draw the name with")?;
    let (font, metrics) = (MIN_TEXT_PX..=theme.text_px(HEIGHT * 4))
        .rev()
        .find_map(|px| {
            let font = ttf.load_font(&path, f32::from(px)).ok()?;
            let metrics = measure_line(&font, &["Karaoke", "Machine"]);
            (metrics.width <= available).then_some((font, metrics))
        })
        .ok_or("the name does not fit beside the icon at any readable size")?;

    let left = text_left + (available - metrics.width) / 2.0;
    let top = (HEIGHT as f32 - metrics.height) / 2.0;
    draw_text(
        &mut canvas,
        &mut cache,
        &font,
        "Karaoke",
        (left, top),
        &TextStyle::plain(theme.lyric_pending, Align::Left),
    );
    draw_text(
        &mut canvas,
        &mut cache,
        &font,
        "Machine",
        (left + metrics.offsets[1], top),
        // The amber, and not the accent blue. See the module comment: the wordmark's second half
        // is amber on the website and on the application icon, and one banner in another color
        // is the odd one out.
        &TextStyle::plain(theme.lyric_sung, Align::Left),
    );
    cache.clear();
    canvas.present();

    let pixels = canvas.read_pixels(None)?;
    let (width, height) = (pixels.width(), pixels.height());
    let rgba = pixels.with_lock(|bytes| {
        // ARGB8888 little-endian is BGRA in memory order.
        let mut out = Vec::with_capacity(bytes.len());
        for chunk in bytes.as_chunks::<4>().0 {
            out.extend_from_slice(&[chunk[2], chunk[1], chunk[0], chunk[3]]);
        }
        out
    });

    let buffer = image::RgbaImage::from_raw(width, height, rgba)
        .ok_or("the pixel buffer was the wrong size")?;
    buffer.save(&out)?;
    println!("wrote {} ({width}x{height})", out.display());
    Ok(())
}

/// Loads `icon/icon-128.png` as a texture ready to blit.
///
/// 128 rather than 256 because the banner draws it at 130 pixels; taking the next size up and letting
/// the GPU downscale it would be softer than the rendering the icon example already made at
/// approximately the right size.
///
/// Generic over the creator's context because this canvas is backed by a `Surface`, not a `Window` —
/// the banner is rendered without a screen.
fn icon_texture<T>(
    creator: &sdl3::render::TextureCreator<T>,
) -> Result<sdl3::render::Texture, Box<dyn std::error::Error>> {
    let decoded = image::open("icon/icon-128.png")?.to_rgba8();
    let (width, height) = (decoded.width(), decoded.height());
    // `RGBA32` is the format whose memory order is R, G, B, A whatever the machine's endianness,
    // which is what `image` produces — unlike the `ARGB8888` the canvas is read back as above, which
    // is a *channel* order and therefore reversed in memory here.
    let format = PixelFormat::try_from(sdl3::sys::pixels::SDL_PIXELFORMAT_RGBA32)?;
    let mut pixels = decoded.into_raw();
    let surface = Surface::from_data(&mut pixels, width, height, width * 4, format)?;
    Ok(creator.create_texture_from_surface(&surface)?)
}
