/*
 * The offline remote's C surface — the pair of `src/ffi.rs`.
 *
 * Hand-written and committed, rather than generated by cbindgen: that is another tool to install, a
 * config file, a pinned version and a build step, for six declarations whose whole design principle
 * is that they never grow. `tests/header_matches.rs` is what stops this drifting from the Rust —
 * a C symbol has no mangling, so a changed *signature* still links and would go wrong only on a
 * device.
 *
 * The Swift side reaches these through `KaraokeRemote-Bridging-Header.h`.
 *
 * Threading: every function here may be called from any thread and none of them blocks.
 * `km_remote_stop` in particular returns at once rather than waiting for the server to wind down,
 * which is what makes it safe to call from `applicationWillTerminate`.
 */

#ifndef KM_REMOTE_H
#define KM_REMOTE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Starts the server and returns immediately. Poll km_remote_port for the result.
 *
 * A no-op if a run is already going, which is what makes it safe to call without checking first.
 *
 * data_dir  the directory holding the two databases. Created by the caller; never derived here.
 * machine   an address somebody typed, or NULL to look for one. NAMING ONE PINS IT — the server
 *           will not wander to another machine afterwards, so a caller offering this must also
 *           offer a way to clear it.
 *
 * Both strings are copied before this returns, so the caller may free them immediately. (Swift's
 * `withCString` does exactly that, and a library that read them later would be reading freed
 * memory.)
 */
void km_remote_start(const char *data_dir, const char *machine);

/* The port the remote is answering on, or 0 until it is. */
int32_t km_remote_port(void);

/*
 * How many songs this device's copy of the catalog holds, or -1 if that is not known yet.
 *
 * Zero is a real answer: a first run that found no machine and has nothing to show.
 */
int32_t km_remote_songs(void);

/*
 * Why the remote stopped, or NULL while it is healthy.
 *
 * The string belongs to this library. DO NOT FREE IT, and copy it before the next call.
 */
const char *km_remote_failure(void);

/*
 * The machine this run is talking to, or NULL — which is ordinary and is not a failure.
 *
 * The string belongs to this library. DO NOT FREE IT, and copy it before the next call.
 */
const char *km_remote_machine(void);

/* Asks the server to stop, and returns at once. */
void km_remote_stop(void);

#ifdef __cplusplus
}
#endif

#endif /* KM_REMOTE_H */
